### ISSUE TITLE
#2 Inception

### ISSUE THREAD

**Issue by eranhd** [malkals/Yedidim#5]
**Readme**
- No link to chat room
- No link to relevant documents
- Why is the project itself located in another library?

Diagram classes are very thin
Basically, you do not believe you can get to the fifth iteration, but the planning is fine

grade 90

**Comment by riki-r** [comment]
לא הבנו למה הורד לנו נקודות על זה:
יש לנו קישור לchat room בread me
לאיזה מסמכים אין קישורים?
הפרויקט קישרנו לספריה אחרת כי כתוב בתרגיל שלבינתיים ניתן לקשר לתרגיל שעשינו: קישור להפצה נוכחית של עמוד מוצר (אפשר בשלב זה לאחד מעמודי הדוגמא שהעליתם במסגרת משימת ההיכרות עם סביבת הפיתוח או האב-טיפוס)
@eranhd

**Comment by sarafaust** [comment]
מה אנחנו אמורות להוסיף ל
?class diagrams

**Comment by sarafaust** [comment]
@eranhd 
מה אנחנו אמורות להוסיף ל
?class diagrams

**Comment by sarafaust** [comment]
@eranhd @robi-y 
אפשר קצת עזרה עם ה 
class diagrams 
מה בדיוק אנחנו אמורות להוסיף?
משתנים, פונקציות

**Comment by Aviya-B** [comment]
SRS review
- [x]  change class diagrams

**Comment by robi-y** [comment]
Please comment on the correct issue
